// ==================== BUFF DESCRIPTIONS ====================
const buffDescriptions = {
  "Souper Satisfied": "Basic soup buff. Provides standard hunger and thirst restoration.",
  "Bodacious": "Provides all benefits of Souper Satisfied PLUS makes your inventory 25% lighter (like having Carbuncle Balloon equipped).",
  "Heightened Senses": "Hones your reflexes and increases blunt and sharp melee XP gain. Great for quick leveling!",
  "Mega-Ante": "Temporarily increases movement speed and strength. One of the best buffs!",
  "Quick Reflexes": "Provides more XP for accuracy and reloading skills.",
  "Big Brain": "Increases crafting and construction XP. Perfect for long building sessions!",
  "Brain Freeze": "Keeps you cool in warm areas. Useful in hot sectors and portal worlds.",
  "Desire of the Flesh": "Reduces damage taken BUT attracts the Leyak. Use with caution!",
  "Lightfooted": "Increases XP for sprinting and sneaking.",
  "Living Off the Land": "Makes gardening actions give more agricultural XP. Great before planting!",
  "Rad Resistant": "Reduces incoming radiation by 50% PLUS Souper Satisfied benefits. Essential for late-game portal worlds.",
  "Sweet Tooth": "Gives extra boost to hunger and thirst bars when eating vending machine snacks.",
  "Sugar High": "Increases stamina temporarily but makes you tire easily and need bathroom more often.",
  "Well Fed": "Provides sustained energy and health regeneration.",
  "Energized": "Increases stamina regeneration rate."
};

// ==================== IMAGE CONFIGURATION ====================
const imageUrls = {
  ingredients: {
    "Tomato": "https://abioticfactor.wiki.gg/images/Item_Icon_-_Tomato.png?ec852d",
    "Super Tomato": "https://abioticfactor.wiki.gg/images/Item_Icon_-_Super_Tomato.png?8523e3",
    "Salt": "https://abioticfactor.wiki.gg/images/Item_Icon_-_Salt.png?67b806",
    "Raw Peccary Chop": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Peccary_Chop.png/64px-Item_Icon_-_Raw_Peccary_Chop.png?f9644c",
    "Raw Alien Drumstick": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Alien_Drumstick.png/64px-Item_Icon_-_Raw_Alien_Drumstick.png?91de67",
    "Raw Pest": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Pest.png/64px-Item_Icon_-_Raw_Pest.png?7a876c",
    "Canned Peas": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Canned_Peas.png/64px-Item_Icon_-_Canned_Peas.png?2aceaf",
    "Raw Dough": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_food_raw_dough.png/64px-Itemicon_food_raw_dough.png?e81d1e",
    "Raw Carbuncle": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Carbuncle.png/64px-Item_Icon_-_Raw_Carbuncle.png?354396",
    "Purified Corn": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_food_corn.png/64px-Itemicon_food_corn.png?2f2a2f",
    "Milk Sac": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Milk_Sac.png/64px-Item_Icon_-_Milk_Sac.png?7e3309",
    "Raw Larva Meat": "https://abioticfactor.wiki.gg/images/Raw_Larva_Meat.png?9597a3",
    "Carbuncle Mushroom": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Carbuncle_Mushroom.png/64px-Item_Icon_-_Carbuncle_Mushroom.png?d93f23",
    "Antepasta": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Antepasta.png/64px-Item_Icon_-_Antepasta.png?553234",
    "Raw Peccary Sausages": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Peccary_Sausages.png/64px-Item_Icon_-_Raw_Peccary_Sausages.png?4c1f08",
    "Potato": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_potato.png/64px-Itemicon_potato.png?a1fe00",
    "Raw Pest Rump": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Pest_Rump.png/64px-Item_Icon_-_Raw_Pest_Rump.png?d59055",
    "Pumpkin": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_pumpkin.png/64px-Itemicon_pumpkin.png?9e1ab0",
    "Raw Antefish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_antefish_raw.png/64px-Itemicon_filet_antefish_raw.png?1f319e",
    "Raw Chordfish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_fogfish_raw.png/64px-Itemicon_filet_fogfish_raw.png?699555",
    "Xanterium Rice": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_ricebag.png/64px-Itemicon_ricebag.png?10249b",
    "Raw Inkfish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_reaperfish_raw.png/64px-Itemicon_filet_reaperfish_raw.png?798710",
    "Egg": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Egg.png/64px-Item_Icon_-_Egg.png?ae40a7",
    "Raw Moon Fish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_moonfish_raw.png/64px-Itemicon_filet_moonfish_raw.png?23a9fb",
    "Raw Exor Heart": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Exor_Heart.png/64px-Item_Icon_-_Raw_Exor_Heart.png?16ef4c",
    "Raw Portal Fish Fillet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_portalfish_raw.png/64px-Itemicon_filet_portalfish_raw.png?5badbd",
    "Raw Darkwater Fish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_fish_filet_dw_raw.png/64px-Itemicon_fish_filet_dw_raw.png?72a096",
    "Greyeb": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Greyeb.png/64px-Item_Icon_-_Greyeb.png?4fd550",
    "Murkweed": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_seaweed.png/64px-Itemicon_seaweed.png?e3ca1e",
    "Raw Silken Betta Filet": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Silken_Betta_Filet.png/64px-Item_Icon_-_Raw_Silken_Betta_Filet.png?401c56",
    "Raw Penumbra Filet": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Raw_Penumbra_Filet.png/64px-Item_Icon_-_Raw_Penumbra_Filet.png?426f03",
    "Glow Eye": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_GlowEye1.png/64px-Itemicon_GlowEye1.png?9f88e7",
    "Exor Arm": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Exor_Arm.png/64px-Item_Icon_-_Exor_Arm.png?f3c4df",
    "Military MRE": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Military_M.R.E..png/64px-Item_Icon_-_Military_M.R.E..png?dc074b",
    "Raw Frigid Queenfish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_icefish_raw.png/64px-Itemicon_filet_icefish_raw.png?62a4c7",
    "Antiverse Wheat": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Anteverse_Wheat.png/64px-Item_Icon_-_Anteverse_Wheat.png?88dfd6",
    "Raw Radfish Filet": "https://abioticfactor.wiki.gg/images/thumb/Itemicon_filet_radfish_raw.png/64px-Itemicon_filet_radfish_raw.png?3a67d4",
    "Melted Ice Cream": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Melted_Ice_Cream.png/64px-Item_Icon_-_Melted_Ice_Cream.png?e00ceb",
    "Doznuts": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Doznuts.png/64px-Item_Icon_-_Doznuts.png?5a23fc",
    "Jowlers": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Jowlers.png/64px-Item_Icon_-_Jowlers.png?acf8b9",
    "Skip": "https://abioticfactor.wiki.gg/images/thumb/Item_Icon_-_Skip.png/64px-Item_Icon_-_Skip.png?b854be"
  },
  recipes: {}
};

// ==================== RECIPES DATA ====================
const recipes = [
  // SOUPS - Cooking Pot
  {name: "Peccary Goulash", ingredients: ["Raw Peccary Chop", "Raw Alien Drumstick", "Salt"], hunger: 23, thirst: 16, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Simple Tomato Soup", ingredients: ["Tomato", "Salt"], hunger: 12, thirst: 22, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Super Tomato Soup", ingredients: ["Super Tomato", "Salt"], hunger: 15, thirst: 22, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Split Pea Soup", ingredients: ["Canned Peas", "Salt", "Raw Pest"], hunger: 17, thirst: 21, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Carbuncle N' Dumplings", ingredients: ["Raw Dough", "Raw Carbuncle", "Canned Peas"], hunger: 23, thirst: 21, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Creamy Corn Soup", ingredients: ["Purified Corn", "Milk Sac", "Salt"], hunger: 32, thirst: 27, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Creamy Tomato Bisque", ingredients: ["Super Tomato", "Milk Sac", "Salt"], hunger: 12, thirst: 37, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Gooey Mushroom Soup", ingredients: ["Raw Larva Meat", "Carbuncle Mushroom", "Salt"], hunger: 31, thirst: 17, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Homey Pasta", ingredients: ["Antepasta", "Raw Peccary Sausages", "Tomato"], hunger: 33, thirst: 22, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Mashed Potatoes", ingredients: ["Potato", "Milk Sac", "Salt"], hunger: 8, thirst: 33, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Meatrio Medley", ingredients: ["Raw Carbuncle", "Raw Pest Rump", "Raw Alien Drumstick"], hunger: 23, thirst: 16, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Pest Goulash", ingredients: ["Raw Pest", "Raw Pest Rump", "Salt"], hunger: 14, thirst: 16, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Peccary Stew", ingredients: ["Raw Peccary Chop", "Carbuncle Mushroom", "Super Tomato"], hunger: 21, thirst: 23, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Potato and Sausage Stew", ingredients: ["Raw Peccary Sausages", "Potato"], hunger: 20, thirst: 17, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Pumpkin Soup", ingredients: ["Pumpkin", "Milk Sac", "Salt"], hunger: 21, thirst: 25, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Hearty Stew", ingredients: ["Raw Exor Heart", "Carbuncle Mushroom", "Super Tomato"], hunger: 23, thirst: 23, cookingMethod: "soup", buff: "Bodacious"},
  {name: "Meaty Stew", ingredients: ["Raw Peccary Chop", "Raw Alien Drumstick", "Raw Pest Rump"], hunger: 26, thirst: 16, cookingMethod: "soup", buff: "Heightened Senses"},
  {name: "A&L Mega-Stew", ingredients: ["Exor Arm", "Raw Alien Drumstick", "Raw Exor Heart"], hunger: 37, thirst: 16, cookingMethod: "soup", buff: "Mega-Ante"},
  {name: "Sustenance Soup", ingredients: ["Military MRE"], hunger: 18, thirst: 16, cookingMethod: "soup", buff: "Quick Reflexes"},
  {name: "Balanced Stew", ingredients: ["Raw Carbuncle", "Carbuncle Mushroom", "Salt"], hunger: 13, thirst: 17, cookingMethod: "soup", buff: "Big Brain"},
  {name: "Greyeb Chowder", ingredients: ["Greyeb", "Milk Sac", "Potato"], hunger: 12, thirst: 42, cookingMethod: "soup", buff: "Desire of the Flesh"},
  {name: "Bland Pea Soup", ingredients: ["Canned Peas", "Salt"], hunger: 12, thirst: 21, cookingMethod: "soup", buff: "Lightfooted"},
  {name: "Veggie Stew", ingredients: ["Potato", "Antiverse Wheat", "Super Tomato"], hunger: 17, thirst: 24, cookingMethod: "soup", buff: "Living Off the Land"},
  {name: "Sweet Porridge", ingredients: ["Melted Ice Cream", "Antiverse Wheat"], hunger: 10, thirst: 24, cookingMethod: "soup", buff: "Sweet Tooth"},
  {name: "Sugary Slop", ingredients: ["Doznuts", "Jowlers", "Skip"], hunger: 18, thirst: 17, cookingMethod: "soup", buff: "Sugar High"},
  {name: "Anteverse Gumbo", ingredients: ["Raw Antefish Filet", "Raw Peccary Sausages", "Potato"], hunger: 25, thirst: 17, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Harmonious Rice", ingredients: ["Raw Chordfish Filet", "Milk Sac", "Xanterium Rice"], hunger: 25, thirst: 31, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Inky Egg Drop Soup", ingredients: ["Raw Inkfish Filet", "Egg", "Carbuncle Mushroom"], hunger: 23, thirst: 22, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Lunar Bisque", ingredients: ["Raw Moon Fish Filet", "Raw Exor Heart", "Carbuncle Mushroom"], hunger: 23, thirst: 17, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Portal Fish Stew", ingredients: ["Raw Portal Fish Fillet", "Tomato", "Potato"], hunger: 21, thirst: 24, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Reservoir Reserve", ingredients: ["Raw Darkwater Fish Filet", "Greyeb", "Murkweed"], hunger: 21, thirst: 25, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Silky Consommé", ingredients: ["Raw Silken Betta Filet", "Egg", "Salt"], hunger: 38, thirst: 21, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Witching Hour Brew", ingredients: ["Raw Penumbra Filet", "Glow Eye", "Carbuncle Mushroom"], hunger: 42, thirst: 17, cookingMethod: "soup", buff: "Souper Satisfied"},
  {name: "Glacial Gazpacho", ingredients: ["Raw Frigid Queenfish Filet", "Pumpkin", "Greyeb"], hunger: 30, thirst: 25, cookingMethod: "soup", buff: "Brain Freeze"},
  {name: "Radfish Chowder", ingredients: ["Raw Radfish Filet", "Potato", "Canned Peas"], hunger: 23, thirst: 22, cookingMethod: "soup", buff: "Rad Resistant"},

  // FRYING - Frying Pan
  {name: "Cooked Carbuncle", ingredients: ["Raw Carbuncle"], hunger: 10, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Pest", ingredients: ["Raw Pest"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Pest Rump", ingredients: ["Raw Pest Rump"], hunger: 18, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Peccary Chop", ingredients: ["Raw Peccary Chop"], hunger: 15, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Peccary Sausages", ingredients: ["Raw Peccary Sausages"], hunger: 15, thirst: 5, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Alien Drumstick", ingredients: ["Raw Alien Drumstick"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Exor Heart", ingredients: ["Raw Exor Heart"], hunger: 18, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Fried Egg", ingredients: ["Egg"], hunger: 18, thirst: 6, cookingMethod: "frying", buff: "Energized"},
  {name: "Cooked Antefish Filet", ingredients: ["Raw Antefish Filet"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Chordfish Filet", ingredients: ["Raw Chordfish Filet"], hunger: 18, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Portal Fish Filet", ingredients: ["Raw Portal Fish Fillet"], hunger: 11, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Inkfish Filet", ingredients: ["Raw Inkfish Filet"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Radfish Filet", ingredients: ["Raw Radfish Filet"], hunger: 11, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Moon Fish Filet", ingredients: ["Raw Moon Fish Filet"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Darkwater Fish Filet", ingredients: ["Raw Darkwater Fish Filet"], hunger: 10, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Silken Betta Filet", ingredients: ["Raw Silken Betta Filet"], hunger: 20, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Penumbra Filet", ingredients: ["Raw Penumbra Filet"], hunger: 22, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},
  {name: "Cooked Frigid Queenfish Filet", ingredients: ["Raw Frigid Queenfish Filet"], hunger: 12, thirst: 0, cookingMethod: "frying", buff: "Well Fed"},

  // OVEN/BAKING
  {name: "Bread", ingredients: ["Raw Dough"], hunger: 12, thirst: 5, cookingMethod: "oven", buff: "Energized"},
  {name: "Pumpkin Bread", ingredients: ["Pumpkin", "Raw Dough"], hunger: 37, thirst: 5, cookingMethod: "oven", buff: "Energized"},
  {name: "Baked Potato", ingredients: ["Potato"], hunger: 10, thirst: 3, cookingMethod: "oven", buff: "Energized"},
  {name: "Roasted Pumpkin", ingredients: ["Pumpkin"], hunger: 20, thirst: 7, cookingMethod: "oven", buff: "Energized"}
];
